### ISSUE TITLE
Uncaught TypeError: this.function._equals is not a function

### ISSUE THREAD

**Issue by renggli** [dart-lang/webdev#1291]
Function equality throws a TypeError in `webdev serve` mode: `Uncaught TypeError: this.function._equals is not a function`. The field is declared as `final Function function` and initialized with a tear-off function from an object.

The same code works as expected when run with `webdev build` or when exercising the JS code using `dart run test --platform=vm,nodejs,chrome,firefox`.

- Dart SDK version: 2.12.2 (stable)
- webdev 2.7.2

**Comment by grouma** [comment]
Can you provide a small sample program in which this problem occurs?

cc @jakemac53

**Comment by jakemac53** [comment]
If we could get a stack trace that would also be helpful

**Comment by renggli** [comment]
This is the minimal  example I can come up with that reproduces the error:

# index.dart

```dart
class Wrapper {
  Wrapper(this.function);

  final Function function;

  @override
  bool operator ==(Object other) =>
      other is Wrapper && other.function == other.function;

  @override
  int get hashCode => function.hashCode;
}

void main() {
  final map = <Wrapper, int>{};
  final ref = Wrapper(main);
  map[ref] = 42;
  print(map[ref]);
}
```

# index.html

```html
<!DOCTYPE html>
<html>
<body>
  <script src="index.dart.js"></script>
</body>
</html>
```

# Failure case

Run with `webdev serve --debug` yields the following stack trace:

```
Uncaught TypeError: other.function._equals is not a function
    at index.Wrapper.new._equals (index.dart:8)
    at Object.equals (operations.dart:687)
    at LinkedMap.new._get (linked_hash_map.dart:147)
    at main (index.dart:18)
    at index.dart.bootstrap.js:267
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (index.dart.bootstrap.js:266)
    at <anonymous>:1:8
    at Object.runMain (client.js:8777)
    at client.js:22469
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3824)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:11013)
    at Object._asyncStartSync (client.js:3788)
    at main__closure1.$call$body$main__closure (client.js:22481)
    at main__closure1.call$1 (client.js:22408)
    at StaticClosure._rootRunUnary [as call$2$5] (client.js:4154)
    at _CustomZone.runUnary$2$2 (client.js:12369)
    at _CustomZone.runUnaryGuarded$1$2 (client.js:12312)
    at _ControllerSubscription._sendData$1 (client.js:11909)
    at _DelayedData.perform$1 (client.js:12098)
    at _PendingEvents_schedule_closure.call$0 (client.js:12147)
    at Object._microtaskLoop (client.js:3995)
    at StaticClosure._startMicrotaskLoop (client.js:4001)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (client.js:10882)
    at invokeClosure (client.js:1260)
    at MutationObserver.<anonymous> (client.js:1279)
```

# Success  case

Run with `webdev serve --release` prints `42`.

**Comment by grouma** [comment]
I'm wondering if this has something to do with how we [hoist](https://github.com/dart-lang/webdev/blob/18440bfd54861c2b98ba7934e5456f6d78b018a1/dwds/lib/src/handlers/injector.dart#L161) main. @jakemac53 thoughts on if this could be the case?

**Comment by renggli** [comment]
The problem is not specific to the main method used here. This is the place where I originally discovered it: https://github.com/petitparser/dart-petitparser/blob/main/petitparser_examples/lib/src/lisp/parser.dart#L8. The error happens here: https://github.com/petitparser/dart-petitparser/blob/main/petitparser/lib/src/definition/reference.dart#L19

**Comment by grouma** [comment]
@renggli this is a runtime issue correct? That error you are seeing is in the Chrome console, not the Webdev CLI? Since this works with `webdev serve --release` it's potentially a DDC issue.

cc @nshahan @Markzipan

**Comment by renggli** [comment]
Yes, a runtime issue. Stack trace and output are in the developer console of Chrome. The problem doesn't happen when running the same code with `dart run test --platform=chrome`.

**Comment by nshahan** [comment]
I haven't been able to reproduce the issue with the minimal example you posted when compiling with DDC outside of the webdev environment. What does your compiled javascript code look like for the Wrapper class? I see:
```javascript
test_03.Wrapper = class Wrapper extends core.Object {
  get function() {
    return this[$function$];
  }
  set function(value) {
    super.function = value;
  }
  _equals(other) {
    if (other == null) return false;
    return test_03.Wrapper.is(other) && dart.equals(this.function, other.function);
  }
  get hashCode() {
    return dart.hashCode(this.function);
  }
};
```

**Comment by grouma** [comment]
Hmmm. I'm having a difficult time reproducing this as well. Using the same SDK and Webdev version as @renggli. I'm running on MacOS. Any other environment details @renggli?

**Comment by renggli** [comment]
MacOS 11.2.3 (20D91). Dart 2.12.2. webdev 2.7.2.

The generated code with `webdev serve --debug` looks different for me:

```javascript
index.Wrapper = class Wrapper extends core.Object {
    get function() {
      return this[$function$];
    }
    set function(value) {
      super.function = value;
    }
    _equals(other) {
      if (other == null) return false;
      return index.Wrapper.is(other) && this.function._equals(other.function);
    }
    get hashCode() {
      return this.function.hashCode;
    }
  };
```

**Comment by renggli** [comment]
Attached [example.zip](https://github.com/dart-lang/webdev/files/6226963/example.zip) with the setup. 

```
$ webdev serve --debug
[INFO] Reading cached asset graph completed, took 167ms
[INFO] Checking for updates since last build completed, took 457ms
[INFO] Serving DevTools at http://127.0.0.1:64905
[INFO] Serving `web` on http://127.0.0.1:8080
[INFO] Running build completed, took 585ms
[INFO] Caching finalized dependency graph completed, took 207ms
[INFO] Succeeded after 804ms with 4 outputs (1262 actions)
[INFO] Injected debugging metadata for entrypoint at http://127.0.0.1:8080/index.dart.bootstrap.js
```

**Comment by drpond1** [comment]
I posted this on petitparser issues page and Lukas Renggli asked me to post it here.

My case of the bug comes from trying to translate an XML file.  Here is my report

 I have been using the xml oub package to easily parse an xml file. But after upgrading my project to 2.12 with the latest xml software I get a typing error, at the beginning of the translation
throwing an exception up to my code.

At my code: var doc = xml.XmlDocument.parse(input);
to the XML parser
final parser = documentParserCache[mapping];
eventually to petit parser
_resolve(Reference(start ?? this.start, arguments)) as Parser;
and then eventually to an exception on equal check

other.function is a f bound document () tested against function

in reference.dart at line 19:

bool operator ==(Object other) {
if (other is Reference) {
if (other.function != function ||

{}other.function._equals is not a function
TypeError: other.function._equals is not a function
at reference$.Reference.new._equals (http://localhost:53322/packages/petitparser/src/definition/grammar.sound.ddc.js:81:29)
at Object.equals (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:5074:47)
at LinkedMap.new._get (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:21993:24)
at _dereference (http://localhost:53322/packages/petitparser/src/definition/grammar.sound.ddc.js:177:36)
at parser$.XmlParserDefinition.new.[_resolve] (http://localhost:53322/packages/petitparser/src/definition/grammar.sound.ddc.js:208:30)
at parser$.XmlParserDefinition.new.build (http://localhost:53322/packages/petitparser/src/definition/grammar.sound.ddc.js:172:49)
at XmlCache.new. (http://localhost:53322/packages/xml/src/xml/entities/default_mapping.sound.ddc.js:2309:174)
at XmlCache.new._get (http://localhost:53322/packages/xml/src/xml/entities/default_mapping.sound.ddc.js:1915:52)
at Function.parse (http://localhost:53322/packages/xml/src/xml/entities/default_mapping.sound.ddc.js:2242:49)
at Object.translateXML (http://localhost:53322/drpond.sound.ddc.js:39699:38)
at http://localhost:53322/drpond.sound.ddc.js:38502:22
at Object._checkAndCall (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:4869:16)
at Object.dcall (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:4874:17)
at FileReader. (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:97033:100)

**Comment by grouma** [comment]
I'm able to reproduce this with the example in https://github.com/dart-lang/webdev/issues/1291#issuecomment-809963262.

This seems like a DDC issue and is unrelated to the injected client. Note the injected client simply calls `main` indirectly.

Here's the exception:
```
Uncaught TypeError: this.function._equals is not a function
    at index.Wrapper.new._equals (index.sound.ddc.js:44)
    at Object.equals (dart_sdk.sound.js:5074)
    at LinkedMap.new._get (dart_sdk.sound.js:21993)
    at main (index.sound.ddc.js:67)
    at index.dart.bootstrap.js:267
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (index.dart.bootstrap.js:266)
    at <anonymous>:1:8
    at Object.runMain (client.js:8777)
    at client.js:22469
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3824)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:11013)
    at Object._asyncStartSync (client.js:3788)
    at main__closure1.$call$body$main__closure (client.js:22481)
    at main__closure1.call$1 (client.js:22408)
    at StaticClosure._rootRunUnary [as call$2$5] (client.js:4154)
    at _CustomZone.runUnary$2$2 (client.js:12369)
    at _CustomZone.runUnaryGuarded$1$2 (client.js:12312)
    at _ControllerSubscription._sendData$1 (client.js:11909)
    at _DelayedData.perform$1 (client.js:12098)
    at _PendingEvents_schedule_closure.call$0 (client.js:12147)
    at Object._microtaskLoop (client.js:3995)
    at StaticClosure._startMicrotaskLoop (client.js:4001)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (client.js:10882)
    at invokeClosure (client.js:1260)
    at MutationObserver.<anonymous> (client.js:1279)
```

The compiled code looks like this:
``` JS
index.Wrapper = class Wrapper extends core.Object {
    get function() {
      return this[$function$];
    }
    set function(value) {
      super.function = value;
    }
    _equals(other) {
      if (other == null) return false;
      return index.Wrapper.is(other) && this.function._equals(other.function);
    }
    get hashCode() {
      return this.function.hashCode;
    }
  };
  ```

It looks like `this.function._equals` is undefined which is definitely unexpected.

@nshahan or @sigmundch can you help investigate?

**Comment by nshahan** [comment]
@grouma Yes we can take a look. That example looks like the same as the one I tried before so I'm not sure why you were able to repro this time. Was there something that you did differently? Did you repro using webdev?

**Comment by Markzipan** [comment]
I managed to get a repro with that zip file (pub get -> webdev serve).

After some exploration, making the following substitution with the runtime equals function (which is just a JS `===`) resolves the issue:
```
      return index.Wrapper.is(other) && dart.equals(this.function, other.function);
      // return index.Wrapper.is(other) && this.function._equals(other.function);
```

This is because DDC doesn't seem to append extension symbols to the `main` function a la:
`  dart.defineExtensionMethods(index.Wrapper, ['_equals'])`

**Comment by grouma** [comment]
> @grouma Yes we can take a look. That example looks like the same as the one I tried before so I'm not sure why you were able to repro this time. Was there something that you did differently? Did you repro using webdev?

Looks like Mark was able to repro. Use the example in https://github.com/dart-lang/webdev/issues/1291#issuecomment-809963262

**Comment by grouma** [comment]
@Markzipan so is this a DDC issue? Can you transfer this over to the SDK if so?

**Comment by nshahan** [comment]
The repro uses the `main` function but that was not the case in the original issue report. Let's make sure we don't special case the fix for just the main method.

**Comment by Markzipan** [comment]
Hmm, I'm not 100% sure this is fully a DDC issue yet. I can only repro the issue when I use webdev (and on function besides `main`). The issue goes away using DDB, which is odd. I haven't had enough time to thoroughly debug though.

**Comment by grouma** [comment]
Note that `client.js` is compiled with Dart2JS (on presumably a stale SDK). Could it be a weird interaction between the two?

**Comment by Markzipan** [comment]
Returning to this, I can get a DDC-isolated repro now. This fails in strong mode but passes in weak mode, so this definitely seems to be a DDC bug.
